public with sharing class CF_Actor_KnownFor_DTOcrew {

    @AuraEnabled public boolean adult{ get; set; }
    @AuraEnabled public String backdrop_path{ get; set; }	///2hMt6zKQsvYvH3ZRe8T6RzAD2XB.jpg
    @AuraEnabled public Integer id{ get; set; }	//87
    @AuraEnabled public String original_language{ get; set; }	//en
    @AuraEnabled public String original_title{ get; set; }	//Indiana Jones and the Temple of Doom
    @AuraEnabled public String overview{ get; set; }	//After arriving in India, Indiana Jones is asked by a desperate village to find a mystical stone. He agrees – and stumbles upon a secret cult plotting a terrible plan in the catacombs of an ancient palace.
    @AuraEnabled public String poster_path{ get; set; }	///qMTFkksVVGEgXcyFJILERDJsPlv.jpg
    @AuraEnabled public String release_date{ get; set; }	//1984-05-23
    @AuraEnabled public String title{ get; set; }	//Indiana Jones and the Temple of Doom
    @AuraEnabled public boolean video{ get; set; }
    @AuraEnabled public Double vote_average{ get; set; }	//7.3
    @AuraEnabled public Integer vote_count{ get; set; }	//6916
    @AuraEnabled public Double popularity{ get; set; }	//29.165
    @AuraEnabled public String credit_id{ get; set; }	//52fe4215c3a36847f8002c5d
    @AuraEnabled public String department{ get; set; }	//Production
    @AuraEnabled public String job{ get; set; }	//Casting
}