public with sharing class CF_MovieCredits_DTOcrew {

      @AuraEnabled public boolean adult { get; set; }
      @AuraEnabled public Integer gender { get; set; }    //2
      @AuraEnabled public Integer id { get; set; }    //1705
      @AuraEnabled public String known_for_department { get; set; }    //Writing
      @AuraEnabled public String name { get; set; }    //Ted Elliott
      @AuraEnabled public String original_name { get; set; }    //Ted Elliott
      @AuraEnabled public Double popularity { get; set; }    //1.527
//          @AuraEnabled public cls_profile_path profile_path { get; set; }
      @AuraEnabled public String credit_id { get; set; }    //5aa7bdc90e0a263dc701cd81
      @AuraEnabled public String department { get; set; }    //Writing
      @AuraEnabled public String job { get; set; }    //Writer

}